### ISSUE TITLE
Redirected to Questionnaire?

### ISSUE THREAD

**Issue by mrcaidev** [i-am-henri/henri#1]
Hi, I'm just passing by. I was thinking about visiting your homepage, and maybe getting some inspirations on UI design, but then I noticed [henri.gg](https://henri.gg) was redirected to some questionnaire website. Is this deliberately made so? Just being curious, if yes then just ignore this issue :)

![image](https://github.com/user-attachments/assets/302c8b3a-2682-482f-b452-04c35ed5edc2)

**Comment by i-am-henri** [comment]
Hey, I used this domain a while ago for this study (so I don't have to type in the whole url), if you now access https://henri.gg, you'll see the actual website. If you get still redirected, please use this link for the direct vercel deployment link: https://henri-chi.vercel.app.
